export const metadata = {
  title: "Royal House Check",
  description: "Generated by Next.js",
  icons: {
    icon: "/assets/lhasis-logo.png", 
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div>{children}</div>;
}
